import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, Users as UsersIcon, MessageSquare, Plus, Pin, BellOff, Archive, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, } from "@/components/ui/dropdown-menu";
import { formatTime, computeInitials } from "./helpers";
function ChatRow({ group, active, currentUserId, onlineIds, onSelect, }) {
    const isDirect = group.type === "direct";
    const other = isDirect ? group.members.find((m) => m._id !== currentUserId) : undefined;
    const online = isDirect ? (other ? onlineIds.has(other._id) || other.online : false) : false;
    const preview = group.lastMessage?.text
        ? (group.lastMessage.senderId === currentUserId ? "You: " : "") + group.lastMessage.text
        : isDirect
            ? "No messages yet"
            : `${group.members.length} members`;
    const showUnread = (group.unread ?? 0) > 0 && !group.isMuted;
    return (_jsxs("button", { onClick: () => onSelect(group._id), className: `grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 rounded-lg p-2.5 text-left transition-colors duration-150 ${active ? "bg-primary/8" : "hover:bg-accent"}`, children: [_jsxs("span", { className: "relative grid size-11 shrink-0 place-items-center rounded-full bg-primary/12 text-helper font-semibold text-primary", children: [isDirect ? (computeInitials(group.name)) : (_jsx(UsersIcon, { size: 18, strokeWidth: 1.75 })), online && (_jsx("span", { className: "absolute bottom-0 right-0 size-3 rounded-full border-2 border-card bg-success" }))] }), _jsxs("span", { className: "min-w-0", children: [_jsxs("span", { className: "flex items-center gap-1 truncate text-helper font-medium", children: [group.isPinned && _jsx(Pin, { size: 11, strokeWidth: 2, className: "shrink-0 text-muted-foreground" }), group.isMuted && _jsx(BellOff, { size: 11, strokeWidth: 2, className: "shrink-0 text-muted-foreground" }), _jsx("span", { className: "truncate", children: group.name })] }), _jsx("span", { className: "block truncate text-caption text-muted-foreground", children: preview })] }), _jsxs("span", { className: "flex shrink-0 flex-col items-end gap-1", children: [group.lastMessage?.at && (_jsx("span", { className: "text-[10px] tabular-nums text-muted-foreground", children: formatTime(group.lastMessage.at) })), showUnread ? (_jsx("span", { className: "num inline-block rounded-full bg-primary px-1.5 text-[11px] leading-4 text-primary-foreground", children: group.unread })) : group.isArchived ? (_jsx(Archive, { size: 12, strokeWidth: 1.75, className: "text-muted-foreground" })) : null] })] }));
}
export function ChatSidebar({ groups, activeGroupId, currentUserId, onlineIds, search, onSearchChange, isAdmin, onSelect, onNewGroup, onNewChat, }) {
    const query = search.trim().toLowerCase();
    const filtered = query ? groups.filter((g) => g.name.toLowerCase().includes(query)) : groups;
    const pinned = filtered.filter((g) => g.isPinned && !g.isArchived);
    const main = filtered.filter((g) => !g.isPinned && !g.isArchived);
    const archived = filtered.filter((g) => g.isArchived);
    const renderRows = (list) => list.length === 0 ? null : (_jsx("ul", { className: "space-y-0.5", children: list.map((g) => (_jsx("li", { children: _jsx(ChatRow, { group: g, active: activeGroupId === g._id, currentUserId: currentUserId, onlineIds: onlineIds, onSelect: onSelect }) }, g._id))) }));
    return (_jsxs("aside", { className: "flex h-full flex-col border-r border-border bg-card/50", children: [_jsxs("div", { className: "flex items-center gap-2 p-3", children: [_jsxs("label", { className: "flex flex-1 items-center gap-2 rounded-full border border-border bg-muted/50 px-3 py-2", children: [_jsx(Search, { size: 15, strokeWidth: 1.75, className: "shrink-0 text-muted-foreground" }), _jsx("input", { type: "search", "aria-label": "Search conversations", placeholder: "Search chats", value: search, onChange: (e) => onSearchChange(e.target.value), className: "min-w-0 flex-1 bg-transparent text-helper outline-none" })] }), _jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsx(Button, { variant: "outline", size: "icon", className: "size-10 shrink-0 rounded-full", title: "New conversation", children: _jsx(Plus, { size: 17, strokeWidth: 1.75 }) }) }), _jsxs(DropdownMenuContent, { align: "end", className: "w-48", children: [isAdmin && (_jsxs(DropdownMenuItem, { onClick: onNewGroup, children: [_jsx(UsersIcon, { size: 15, strokeWidth: 1.75, className: "mr-2" }), "New group"] })), _jsxs(DropdownMenuItem, { onClick: onNewChat, children: [_jsx(MessageSquare, { size: 15, strokeWidth: 1.75, className: "mr-2" }), "New chat"] })] })] })] }), _jsxs("div", { className: "min-h-0 flex-1 space-y-4 overflow-y-auto px-3 pb-3", children: [pinned.length > 0 && (_jsxs("div", { children: [_jsx("p", { className: "mb-1 px-2 text-[11px] font-medium uppercase tracking-wide text-muted-foreground", children: "Pinned" }), renderRows(pinned)] })), main.length > 0 && renderRows(main), archived.length > 0 && (_jsxs("div", { children: [_jsx("p", { className: "mb-1 px-2 text-[11px] font-medium uppercase tracking-wide text-muted-foreground", children: "Archived" }), renderRows(archived)] })), filtered.length === 0 && (_jsxs("div", { className: "flex flex-col items-center gap-2 py-12 text-center", children: [_jsx(UserPlus, { size: 28, strokeWidth: 1.25, className: "text-muted-foreground/40" }), _jsx("p", { className: "text-helper text-muted-foreground", children: query ? "No chats match your search" : "No conversations yet" })] }))] })] }));
}
