import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Send, Paperclip, Smile, X, Reply, Loader2 } from "lucide-react";
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from "@/components/ui/tooltip";
import { EMOJI_PICKER_EMOJIS } from "./helpers";
export function MessageComposer({ value, onChange, onSend, isSending, replyTo, onCancelReply, typingNames, onTyping, inputRef, }) {
    const handleSubmit = (e) => {
        e.preventDefault();
        onSend();
    };
    return (_jsx(TooltipProvider, { delayDuration: 200, children: _jsxs("div", { className: "border-t border-border bg-card/70 px-3 py-2", children: [replyTo && (_jsxs("div", { className: "mb-2 flex items-center gap-2 rounded-lg border-l-2 border-primary bg-primary/5 px-3 py-2", children: [_jsx(Reply, { size: 14, strokeWidth: 1.75, className: "shrink-0 text-primary" }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsxs("p", { className: "text-caption font-medium text-primary", children: ["Replying to ", replyTo.sender.name] }), _jsx("p", { className: "truncate text-caption text-muted-foreground", children: replyTo.text })] }), _jsx("button", { type: "button", onClick: onCancelReply, className: "text-muted-foreground transition-colors hover:text-foreground", "aria-label": "Cancel reply", children: _jsx(X, { size: 16, strokeWidth: 1.75 }) })] })), typingNames.length > 0 && (_jsxs("div", { className: "mb-1.5 px-1 text-caption italic text-muted-foreground", children: [typingNames.join(", "), " ", typingNames.length === 1 ? "is" : "are", " typing\u2026"] })), _jsxs("form", { className: "flex items-center gap-1.5", onSubmit: handleSubmit, children: [_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx("span", { className: "inline-flex", children: _jsx("button", { type: "button", disabled: true, "aria-label": "Attach file", className: "grid size-11 shrink-0 place-items-center rounded-full text-muted-foreground/50", children: _jsx(Paperclip, { size: 19, strokeWidth: 1.75 }) }) }) }), _jsx(TooltipContent, { children: "File sharing arrives with NAS integration" })] }), _jsxs(Popover, { children: [_jsx(PopoverTrigger, { asChild: true, children: _jsx("button", { type: "button", "aria-label": "Emoji", className: "grid size-11 shrink-0 place-items-center rounded-full text-muted-foreground transition-colors duration-150 hover:bg-accent hover:text-foreground", children: _jsx(Smile, { size: 19, strokeWidth: 1.75 }) }) }), _jsx(PopoverContent, { className: "w-64 p-2", sideOffset: 8, children: _jsx("div", { className: "grid grid-cols-8 gap-1", children: EMOJI_PICKER_EMOJIS.map((emoji) => (_jsx("button", { type: "button", onClick: () => {
                                                onChange(value + emoji);
                                                inputRef.current?.focus();
                                            }, className: "rounded p-1 text-2xl transition-transform hover:scale-125", children: emoji }, emoji))) }) })] }), _jsx("input", { ref: inputRef, "aria-label": "Message", placeholder: "Write a message\u2026", value: value, onChange: (e) => {
                                onChange(e.target.value);
                                onTyping();
                            }, className: "min-w-0 flex-1 rounded-full border border-border bg-muted/50 px-4 py-3 text-helper outline-none transition-shadow focus:ring-2 focus:ring-ring/40" }), _jsx("button", { type: "submit", "aria-label": "Send message", disabled: !value.trim() || isSending, className: "gradient-primary grid size-11 shrink-0 place-items-center rounded-full text-primary-foreground shadow-soft transition-transform duration-200 hover:-translate-y-0.5 disabled:opacity-50 disabled:hover:translate-y-0", children: isSending ? _jsx(Loader2, { size: 18, className: "animate-spin" }) : _jsx(Send, { size: 18, strokeWidth: 1.75 }) })] })] }) }));
}
