import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from "@/lib/utils";
export function SectionCard({ title, description, icon: Icon, action, children, className, bodyClassName, }) {
    return (_jsxs("section", { className: cn("rounded-lg border border-border bg-card p-6 shadow-soft transition-shadow duration-200", className), children: [_jsxs("header", { className: "grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4", children: [_jsxs("div", { className: "flex min-w-0 items-start gap-3", children: [Icon ? (_jsx("span", { className: "grid size-10 shrink-0 place-items-center rounded-md bg-primary/10 text-primary", children: _jsx(Icon, { size: 20, strokeWidth: 1.75 }) })) : null, _jsxs("div", { className: "min-w-0", children: [_jsx("h2", { className: "truncate text-title font-semibold", children: title }), description ? (_jsx("p", { className: "mt-0.5 text-helper text-muted-foreground", children: description })) : null] })] }), action] }), _jsx("div", { className: cn("mt-5", bodyClassName), children: children })] }));
}
export function StatCard({ label, value, hint, icon: Icon, accent = false, }) {
    return (_jsxs("article", { className: cn("lift rounded-lg border p-6", accent
            ? "gradient-primary border-transparent text-primary-foreground shadow-lift"
            : "border-border bg-card shadow-soft"), children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsx("p", { className: cn("text-helper font-medium", accent ? "opacity-90" : "text-muted-foreground"), children: label }), _jsx("span", { className: cn("grid size-9 shrink-0 place-items-center rounded-md", accent ? "bg-white/20" : "bg-primary/10 text-primary"), children: _jsx(Icon, { size: 18, strokeWidth: 1.75 }) })] }), _jsx("p", { className: "num mt-4 text-page font-semibold tracking-tight", children: value }), hint ? (_jsx("p", { className: cn("mt-1 text-caption", accent ? "opacity-85" : "text-muted-foreground"), children: hint })) : null] }));
}
export function EmptyState({ icon: Icon, title, message, action, }) {
    return (_jsxs("div", { className: "flex flex-col items-center rounded-lg border border-dashed border-border bg-card/60 px-6 py-14 text-center", children: [_jsx("span", { className: "grid size-16 place-items-center rounded-full bg-primary/10 text-primary", children: _jsx(Icon, { size: 26, strokeWidth: 1.75 }) }), _jsx("h3", { className: "mt-4 text-title font-semibold", children: title }), _jsx("p", { className: "mt-1 max-w-sm text-helper text-muted-foreground", children: message }), action ? _jsx("div", { className: "mt-5", children: action }) : null] }));
}
