/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as AdminRouteImport } from './routes/_admin';
import { Route as ShellRouteImport } from './routes/_shell';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ShellIndexRouteImport } from './routes/_shell/index';
import { Route as ShellCalendarRouteImport } from './routes/_shell/calendar';
import { Route as ShellChatRouteImport } from './routes/_shell/chat';
import { Route as ShellDocumentsRouteImport } from './routes/_shell/documents';
import { Route as ShellReportsRouteImport } from './routes/_shell/reports';
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings';
import { Route as ShellTasksRouteImport } from './routes/_shell/tasks';
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index';
import { Route as AdminAdminApprovalsRouteImport } from './routes/_admin/admin.approvals';
import { Route as AdminAdminAuditLogsRouteImport } from './routes/_admin/admin.audit-logs';
import { Route as AdminAdminEmployeesRouteImport } from './routes/_admin/admin.employees';
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings';
import { Route as ShellCasesIndexRouteImport } from './routes/_shell/cases.index';
import { Route as ShellCasesCaseIdRouteImport } from './routes/_shell/cases.$caseId';
import { Route as ShellClientsIndexRouteImport } from './routes/_shell/clients.index';
import { Route as ShellClientsClientIdRouteImport } from './routes/_shell/clients.$clientId';
const AdminRoute = AdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => rootRouteImport,
});
const ShellRoute = ShellRouteImport.update({
    id: '/_shell',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const ShellIndexRoute = ShellIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellRoute,
});
const ShellCalendarRoute = ShellCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => ShellRoute,
});
const ShellChatRoute = ShellChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => ShellRoute,
});
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ShellRoute,
});
const ShellReportsRoute = ShellReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ShellRoute,
});
const ShellSettingsRoute = ShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ShellRoute,
});
const ShellTasksRoute = ShellTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ShellRoute,
});
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AdminRoute,
});
const AdminAdminApprovalsRoute = AdminAdminApprovalsRouteImport.update({
    id: '/admin/approvals',
    path: '/admin/approvals',
    getParentRoute: () => AdminRoute,
});
const AdminAdminAuditLogsRoute = AdminAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AdminRoute,
});
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
    id: '/admin/employees',
    path: '/admin/employees',
    getParentRoute: () => AdminRoute,
});
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AdminRoute,
});
const ShellCasesIndexRoute = ShellCasesIndexRouteImport.update({
    id: '/cases/',
    path: '/cases/',
    getParentRoute: () => ShellRoute,
});
const ShellCasesCaseIdRoute = ShellCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => ShellRoute,
});
const ShellClientsIndexRoute = ShellClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => ShellRoute,
});
const ShellClientsClientIdRoute = ShellClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => ShellRoute,
});
const AdminRouteChildren = {
    AdminAdminApprovalsRoute: AdminAdminApprovalsRoute,
    AdminAdminAuditLogsRoute: AdminAdminAuditLogsRoute,
    AdminAdminEmployeesRoute: AdminAdminEmployeesRoute,
    AdminAdminSettingsRoute: AdminAdminSettingsRoute,
    AdminAdminIndexRoute: AdminAdminIndexRoute,
};
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);
const ShellRouteChildren = {
    ShellCalendarRoute: ShellCalendarRoute,
    ShellChatRoute: ShellChatRoute,
    ShellDocumentsRoute: ShellDocumentsRoute,
    ShellReportsRoute: ShellReportsRoute,
    ShellSettingsRoute: ShellSettingsRoute,
    ShellTasksRoute: ShellTasksRoute,
    ShellIndexRoute: ShellIndexRoute,
    ShellCasesCaseIdRoute: ShellCasesCaseIdRoute,
    ShellClientsClientIdRoute: ShellClientsClientIdRoute,
    ShellCasesIndexRoute: ShellCasesIndexRoute,
    ShellClientsIndexRoute: ShellClientsIndexRoute,
};
const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren);
const rootRouteChildren = {
    AdminRoute: AdminRouteWithChildren,
    ShellRoute: ShellRouteWithChildren,
    LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
