import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { X, Loader2, Copy, FileText, ChevronDown, ChevronUp, } from "lucide-react";
import { useVersionHistory } from "@/services/documents";
import { Button } from "@/components/ui/button";
export function VersionHistoryDialog({ open, onClose, documentId, documentName }) {
    const { data, isLoading, isError, error } = useVersionHistory(documentId);
    const [expandedVersion, setExpandedVersion] = useState(null);
    if (!open)
        return null;
    return (_jsxs("div", { className: "fixed inset-0 z-50 flex items-start justify-center overflow-y-auto py-10", children: [_jsx("div", { className: "fixed inset-0 bg-background/80 backdrop-blur-sm", onClick: onClose }), _jsxs("div", { className: "relative z-10 w-full max-w-2xl rounded-xl border border-border bg-card p-6 shadow-lift", children: [_jsxs("div", { className: "mb-6 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-title font-semibold", children: "Version History" }), _jsxs("p", { className: "mt-1 text-helper text-muted-foreground", children: [documentName, " \u2022 ", data?.count ?? 0, " version(s)"] })] }), _jsx("button", { onClick: onClose, className: "grid size-10 place-items-center rounded-sm text-muted-foreground transition-colors hover:bg-accent hover:text-foreground", children: _jsx(X, { size: 19, strokeWidth: 1.75 }) })] }), isLoading ? (_jsx("div", { className: "flex items-center justify-center py-8", children: _jsx(Loader2, { className: "animate-spin text-muted-foreground", size: 20 }) })) : isError ? (_jsxs("div", { className: "rounded-lg border border-destructive/30 bg-destructive/5 p-8 text-center", children: [_jsx("p", { className: "font-medium text-destructive", children: "Failed to load version history" }), _jsx("p", { className: "mt-1 text-helper text-muted-foreground", children: error instanceof Error ? error.message : "Could not connect to the server." })] })) : !data || data.versions.length === 0 ? (_jsx("div", { className: "text-center py-8", children: _jsx("p", { className: "text-helper text-muted-foreground", children: "No version history available" }) })) : (_jsx("div", { className: "space-y-4", children: data.versions.map((version) => (_jsxs("div", { className: "border rounded-lg overflow-hidden", children: [_jsxs("div", { className: "flex items-center justify-between px-5 py-4 border-b border-border bg-muted/50 cursor-pointer", onClick: () => {
                                        setExpandedVersion(expandedVersion === version._id ? null : version._id);
                                    }, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(FileText, { size: 18, className: "text-primary" }), _jsxs("div", { children: [_jsx("p", { className: "font-medium", children: version.name }), _jsxs("p", { className: "text-caption text-muted-foreground", children: ["Version ", version.version || 1, " \u2022 ", version.sizeFormatted || 'Unknown'] })] })] }), _jsxs("div", { className: "flex items-center gap-2 text-caption text-muted-foreground", children: [_jsxs("p", { children: ["Uploaded by: ", typeof version.uploadedBy === 'string'
                                                                    ? version.uploadedBy
                                                                    : version.uploadedBy?.name || 'Unknown'] }), _jsx("p", { children: new Date(version.createdAt).toLocaleDateString("en-IN", { year: 'numeric', month: 'short', day: 'numeric' }) })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Button, { variant: "outline", size: "sm", onClick: (e) => {
                                                        e.stopPropagation();
                                                        navigator.clipboard.writeText(version.sha256 || "");
                                                    }, title: "Copy SHA-256", children: _jsx(Copy, { size: 16 }) }), _jsx("button", { className: `text-caption text-muted-foreground hover:text-foreground ${expandedVersion === version._id ? "rotate-180" : ""}`, onClick: (e) => {
                                                        e.stopPropagation();
                                                        setExpandedVersion(expandedVersion === version._id ? null : version._id);
                                                    }, children: expandedVersion === version._id ? _jsx(ChevronUp, { size: 16 }) : _jsx(ChevronDown, { size: 16 }) })] })] }), expandedVersion === version._id && (_jsx("div", { className: "px-5 py-4 border-t border-border bg-muted/50", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "text-caption text-muted-foreground", children: "SHA-256:" }), _jsx("p", { className: "font-mono text-break", children: version.sha256 })] }), version.caseName && (_jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "text-caption text-muted-foreground", children: "Case:" }), _jsx("p", { className: "font-medium", children: version.caseName })] })), _jsxs("div", { className: "space-y-2", children: [_jsx("p", { className: "text-caption text-muted-foreground", children: "State:" }), _jsx("span", { className: `px-2 py-1 rounded-sm text-xs font-medium ${version.state === "Approved" ? "bg-success/20 text-success" :
                                                            version.state === "Rejected" ? "bg-destructive/20 text-destructive" :
                                                                version.state === "Pending" ? "bg-warning/20 text-warning" :
                                                                    "bg-muted/20 text-muted-foreground"}`, children: version.state })] })] }) }))] }, version._id))) })), _jsx("div", { className: "mt-6 flex justify-end", children: _jsx(Button, { variant: "outline", onClick: onClose, children: "Close" }) })] })] }));
}
